### ISSUE TITLE
Agregar nueva seccion en el portfolio

### ISSUE THREAD

**Issue by gam98** [rviluron752/portfolio-template#1]
# Seccion tecnologias 

Hola, te dejo un preview  de como quedaría la sección de tecnologias en tu portfolio.

![image](https://user-images.githubusercontent.com/78627015/177781242-06dd8d97-0691-49c4-a6de-5e5249b1c9d1.png)

Saludos

**Comment by rviluron752** [comment]
gracias por agregar la nueva seccion... issue cerrado
